Update pom.xml
groovy.lang.GroovyRuntimeException: Conflicting module versions when trying to run test with restasssured. removed groovy dependency from pom because serenity-core and serenity-rest-assured bring that in. excluded it from one though because they come with different versions. not sure if later serenity versions fix that?